services:
  api:
    build: ./api
    environment:
      MIX_ENV: prod
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: timemanager_dev
      DATABASE_URL: ecto://postgres:postgres@db/timemanager_dev
      SECRET_KEY_BASE: secret_key_base
      
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:  ./front/gui
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timemanager_dev

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: