services:
  db:
      image: postgres:15-alpine 
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: timemanager_dev
      ports:
        - "5432:5432"

      volumes:
        - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./api

  frontend:
    build:  ./front/gui
    ports:
      - "8080:80"
    develop:
      watch:
        - action: rebuild
          path: ./front/gui

volumes:
  pgdata: