name: Docker Image CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  docker-build-push-elixir:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "bushyoff"
          password: "dckr_pat_f0V5UlWPzxvLoJpGG6Q2Qf9ILwM"
      -
        name: Build and push elixir
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: bushyoff/t-poo-700-nan_11-elixir:latest
 
  docker-build-push-vuejs:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "bushyoff"
          password: "dckr_pat_f0V5UlWPzxvLoJpGG6Q2Qf9ILwM"
      -
        name: Build and push vuejs
        uses: docker/build-push-action@v6
        with:
          context: ./front/gui
          push: true
          tags: bushyoff/t-poo-700-nan_11-vuejs:latest